#!/bin/bash

paycode="MGHPCC/INTERN"
billable="Y"
emergency="N"

echo -n "What is your start time? Please enter in 24 hour 00:00 format (times will be rounded to the nearest quarter of an hour: "
read starttime
hourStime=$(echo $starttime | cut -d ":" -f 1)
minuteStime=$(echo $starttime | cut -d ":" -f 2)


if [ "$minuteStime" != "00" -o 	"$minuteStime" != "15" -o "$minuteStime" != "30" -o "$minuteStime" != "45" ]
then
	if [	"$minuteStime" -lt 8 ]
	 then minuteStime="00"
      elif [	"$minuteStime" -lt 23 ]
	 then minuteStime="15"
      elif [	"$minuteStime" -lt 38 ]
	 then minuteStime="30"
      elif [	"$minuteStime" -lt 53 ]
	 then minuteStime="45"
	  elif [	"$minuteStime" -ge 53 ]
	 then
		 hourStime=$(($hourStime + 1))
         minuteStime="00"
	 fi
fi

echo -n "What is your end time? "
read endtime
hourEtime=$(echo $endtime | cut -d ":" -f 1)
minuteEtime=$(echo $endtime | cut -d ":" -f 2)


if [ "$minuteEtime" != "00" -o  "$minuteEtime" != "15" -o "$minuteEtime" != "30" -o "$minuteEtime" != "45" ]
then
    if [    "$minuteEtime" -lt 8 ]
     then minuteEtime="00"
      elif [    "$minuteEtime" -lt 23 ]
     then minuteEtime="15"
      elif [    "$minuteEtime" -lt 38 ]
     then minuteEtime="30"
      elif [    "$minuteEtime" -lt 53 ]
     then minuteEtime="45"
    else
        hourEtime=$(($hourEtime + 1)) 
		minuteEtime="00"
    fi
fi

echo -n "How many hours have you worked? Please enter in decimal format and round to the nearest quarter(ex. 3.75 hours): "
read hours
workHour=$(echo $hours | cut -d "." -f 1)
workMin=$(echo $hours | cut -d "." -f 2) 
if [	"$hours" != *"."	]
then
	if [	"$workMin" != "0" -o "$workMin" != "00" -o "$workMin" != "25" -o "$workMin" != "5" -o "$workMin" != "75" ]
     then
		if [	"$workMin" -lt 13 ]
		 then workMin="0"
		  elif [	"$workMin" -lt 38 ]
		 then workMin="25"
		  elif [	"$workMin" -lt 63 ]
		 then workMin="50"
		  elif [	"$workMin" -lt 88 ]
		 then workMin="75"
		else 
			workHour=$(($workHour + 1))
	
		fi
	fi
fi

#use time check to see if user input for workhours is accurate
		
hoursCheck=$(($hourEtime - $hourStime))
minsCheck=$(($minuteEtime - $minuteStime))
timeCheck=$(())

echo -n "What did you do today? "
read work
if [	-z "$work"	]
then
	echo -n "You must include a description of your work for the day: "
read work
fi

echo "$USER|`date +%F` $hourStime:$minuteStime|`date +%F` $hourEtime:$minuteEtime|$hours|$paycode|$billable|$emergency|$work" 
