#!/bin/bash

paycode="MGHPCC/INTERN"
billable="Y"
emergency="N"

echo -n "Use this program to enter hours. Press q to quit or any other key to continue: "
read check

while [	"$check" != "q" ]
do

echo -n "What is your start time? Please enter in 24 hour 00:00 format (times will be rounded to the nearest quarter of an hour): "
read starttime
 
startHour=$(echo $starttime | cut -d ":" -f 1)
startMin=$(echo $starttime | cut -d ":" -f 2)

while [	-z "$starttime" ] || ! [[ "$starttime" =~ [0-9][0-9]:[0-9][0-9] ]] 
do
	echo -n "Please enter valid start time: "
	read starttime
	startHour=$(echo $starttime | cut -d ":" -f 1)
	startMin=$(echo $starttime | cut -d ":" -f 2)
done


if [ "$startMin" != "00" -o "$startMin" != "15" -o "$startMin" != "30" -o "$startMin" != "45" ]
then
	if [	"$startMin" -lt 8 ]
	 then startMin="00"
      elif [	"$startMin" -lt 23 ]
	 then startMin="15"
      elif [	"$startMin" -lt 38 ]
	 then startMin="30"
      elif [	"$startMin" -lt 53 ]
	 then startMin="45"
	  elif [	"$startMin" -ge 53 ]
	 then
		 startHour=$(($startHour + 1))
         startMin="00"
	 fi
fi

starttime=$(echo "$startHour:$startMin")

echo -n "What is your end time? "
read endtime

endHour=$(echo $endtime | cut -d ":" -f 1)
endMin=$(echo $endtime | cut -d ":" -f 2)


while [ -z "$endtime" ] || ! [[ "$endtime" =~ [0-9][0-9]:[0-9][0-9] ]] 
do
    echo -n "Please enter valid end time: "
    read endtime
    endHour=$(echo $endtime | cut -d ":" -f 1)
    endMin=$(echo $endtime | cut -d ":" -f 2)
done

while [	"$endHour" -lt  "$startHour" ] || [	"$endHour" == $startHour -a "$endMin" -le "$startMin" ] 
do 
	echo -n "Please enter valid end time: "
	read endtime
	
	endHour=$(echo $endtime | cut -d ":" -f 1)
	endMin=$(echo $endtime | cut -d ":" -f 2)
done

if [ "$endMin" != "00" -o  "$endMin" != "15" -o "$endMin" != "30" -o "$endMin" != "45" ]
then
    if [    "$endMin" -lt 8 ]
     then endMin="00"
      elif [    "$endMin" -lt 23 ]
     then endMin="15"
      elif [    "$endMin" -lt 38 ]
     then endMin="30"
      elif [    "$endMin" -lt 53 ]
     then endMin="45"
    else
        endHour=$(($endHour + 1)) 
		endMin="00"
    fi
fi
endtime=$( echo "$endHour:$endMin")

newEnd=`date +%s -d ${endtime}`
newStart=`date +%s -d ${starttime}`

timeSecs=$(echo "$newEnd - $newStart" | bc)
workTime=`date +%H:%M -ud @${timeSecs}`

workHrs=$(echo $workTime | cut -d ":" -f 1)
if [	"$workHrs" != 00 ]
then 
	workHrs=$(echo $workHrs | sed 's/^0*//')
	else
		workHrs=0
fi

workMin=$(echo $workTime | cut -d ":" -f 2)

if [	"$workMin" -lt 8 ]
  then workMin="0"
    elif [	"$workMin" -lt 23 ]
      then workMin="25"
	    elif [	"$workMin" -lt 38 ]
	      then workMin="50"
		    elif [	"$workMin" -lt 53 ]
		      then workMin="75"
			else 
		      workHrs=$(($workHrs + 1))
		fi	

hours=$(echo "$workHrs"."$workMin")

echo -n "What did you do today? "
read work
if [	-z "$work"	]
then
	echo -n "You must include a description of your work for the day: "
read work
fi

echo "$USER|`date +%F` $starttime|`date +%F` $endtime|$hours|$paycode|$billable|$emergency|$work" 


echo -n "Use this program to enter hours. Press q to quit or any other key to continue: "
read check
if	[	"$check" = "q" ]
then
	break
fi
done
